/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as sentinelBatchVerifierSol from "./SentinelBatchVerifier.sol";
export type { sentinelBatchVerifierSol };
