/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SentinelBatchVerifierInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CIRCUIT_STATUS"
      | "batchCommitmentHashes"
      | "getCommitmentHash"
      | "isVerified"
      | "sentinel"
      | "totalBatchesVerified"
      | "verifiedBatches"
      | "verifyBatch"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "BatchVerified"): EventFragment;

  encodeFunctionData(
    functionFragment: "CIRCUIT_STATUS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "batchCommitmentHashes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCommitmentHash",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "sentinel", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalBatchesVerified",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifiedBatches",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyBatch",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CIRCUIT_STATUS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCommitmentHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCommitmentHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sentinel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBatchesVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifiedBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyBatch",
    data: BytesLike
  ): Result;
}

export namespace BatchVerifiedEvent {
  export type InputTuple = [
    batchId: BytesLike,
    commitmentHash: BytesLike,
    checksCount: BigNumberish,
    verifiedAt: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    commitmentHash: string,
    checksCount: bigint,
    verifiedAt: bigint
  ];
  export interface OutputObject {
    batchId: string;
    commitmentHash: string;
    checksCount: bigint;
    verifiedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SentinelBatchVerifier extends BaseContract {
  connect(runner?: ContractRunner | null): SentinelBatchVerifier;
  waitForDeployment(): Promise<this>;

  interface: SentinelBatchVerifierInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CIRCUIT_STATUS: TypedContractMethod<[], [string], "view">;

  batchCommitmentHashes: TypedContractMethod<
    [arg0: BytesLike],
    [string],
    "view"
  >;

  getCommitmentHash: TypedContractMethod<
    [batchId: BytesLike],
    [string],
    "view"
  >;

  isVerified: TypedContractMethod<[batchId: BytesLike], [boolean], "view">;

  sentinel: TypedContractMethod<[], [string], "view">;

  totalBatchesVerified: TypedContractMethod<[], [bigint], "view">;

  verifiedBatches: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  verifyBatch: TypedContractMethod<
    [proofData: BytesLike, batchId: BytesLike, checksCount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CIRCUIT_STATUS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "batchCommitmentHashes"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getCommitmentHash"
  ): TypedContractMethod<[batchId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[batchId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "sentinel"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalBatchesVerified"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifiedBatches"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyBatch"
  ): TypedContractMethod<
    [proofData: BytesLike, batchId: BytesLike, checksCount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getEvent(
    key: "BatchVerified"
  ): TypedContractEvent<
    BatchVerifiedEvent.InputTuple,
    BatchVerifiedEvent.OutputTuple,
    BatchVerifiedEvent.OutputObject
  >;

  filters: {
    "BatchVerified(bytes32,bytes32,uint256,uint256)": TypedContractEvent<
      BatchVerifiedEvent.InputTuple,
      BatchVerifiedEvent.OutputTuple,
      BatchVerifiedEvent.OutputObject
    >;
    BatchVerified: TypedContractEvent<
      BatchVerifiedEvent.InputTuple,
      BatchVerifiedEvent.OutputTuple,
      BatchVerifiedEvent.OutputObject
    >;
  };
}
