/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC8004ValidationRegistry__factory } from "./ERC8004ValidationRegistry__factory";
export { IVerifier__factory } from "./IVerifier__factory";
