/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ERC8004ReputationRegistry {
  export type FeedbackEntryStruct = {
    agentId: BigNumberish;
    taskId: BytesLike;
    scoreFixed: BigNumberish;
    decimals: BigNumberish;
    metadataCID: string;
    submitter: AddressLike;
    timestamp: BigNumberish;
  };

  export type FeedbackEntryStructOutput = [
    agentId: bigint,
    taskId: string,
    scoreFixed: bigint,
    decimals: bigint,
    metadataCID: string,
    submitter: string,
    timestamp: bigint
  ] & {
    agentId: bigint;
    taskId: string;
    scoreFixed: bigint;
    decimals: bigint;
    metadataCID: string;
    submitter: string;
    timestamp: bigint;
  };
}

export interface ERC8004ReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "feedbackLog"
      | "getAverageScore"
      | "getFeedback"
      | "getFeedbackCount"
      | "owner"
      | "submitFeedback"
      | "taskSubmitted"
      | "totalFeedbackEntries"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "FeedbackSubmitted"): EventFragment;

  encodeFunctionData(
    functionFragment: "feedbackLog",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAverageScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedback",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedbackCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitFeedback",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "taskSubmitted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeedbackEntries",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "feedbackLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAverageScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedbackCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitFeedback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeedbackEntries",
    data: BytesLike
  ): Result;
}

export namespace FeedbackSubmittedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    taskId: BytesLike,
    scoreFixed: BigNumberish,
    decimals: BigNumberish,
    metadataCID: string,
    submitter: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    taskId: string,
    scoreFixed: bigint,
    decimals: bigint,
    metadataCID: string,
    submitter: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    taskId: string;
    scoreFixed: bigint;
    decimals: bigint;
    metadataCID: string;
    submitter: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC8004ReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ERC8004ReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ERC8004ReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  feedbackLog: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, string, bigint] & {
        agentId: bigint;
        taskId: string;
        scoreFixed: bigint;
        decimals: bigint;
        metadataCID: string;
        submitter: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getAverageScore: TypedContractMethod<
    [agentId: BigNumberish],
    [[bigint, bigint] & { avg: bigint; decimals_: bigint }],
    "view"
  >;

  getFeedback: TypedContractMethod<
    [agentId: BigNumberish, index: BigNumberish],
    [ERC8004ReputationRegistry.FeedbackEntryStructOutput],
    "view"
  >;

  getFeedbackCount: TypedContractMethod<
    [agentId: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  submitFeedback: TypedContractMethod<
    [
      agentId: BigNumberish,
      taskId: BytesLike,
      scoreFixed: BigNumberish,
      decimals_: BigNumberish,
      metadataCID: string
    ],
    [void],
    "nonpayable"
  >;

  taskSubmitted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  totalFeedbackEntries: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "feedbackLog"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [bigint, string, bigint, bigint, string, string, bigint] & {
        agentId: bigint;
        taskId: string;
        scoreFixed: bigint;
        decimals: bigint;
        metadataCID: string;
        submitter: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAverageScore"
  ): TypedContractMethod<
    [agentId: BigNumberish],
    [[bigint, bigint] & { avg: bigint; decimals_: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedback"
  ): TypedContractMethod<
    [agentId: BigNumberish, index: BigNumberish],
    [ERC8004ReputationRegistry.FeedbackEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedbackCount"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitFeedback"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      taskId: BytesLike,
      scoreFixed: BigNumberish,
      decimals_: BigNumberish,
      metadataCID: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskSubmitted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalFeedbackEntries"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "FeedbackSubmitted"
  ): TypedContractEvent<
    FeedbackSubmittedEvent.InputTuple,
    FeedbackSubmittedEvent.OutputTuple,
    FeedbackSubmittedEvent.OutputObject
  >;

  filters: {
    "FeedbackSubmitted(uint256,bytes32,int128,uint8,string,address,uint256)": TypedContractEvent<
      FeedbackSubmittedEvent.InputTuple,
      FeedbackSubmittedEvent.OutputTuple,
      FeedbackSubmittedEvent.OutputObject
    >;
    FeedbackSubmitted: TypedContractEvent<
      FeedbackSubmittedEvent.InputTuple,
      FeedbackSubmittedEvent.OutputTuple,
      FeedbackSubmittedEvent.OutputObject
    >;
  };
}
