/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc8004ValidationRegistrySol from "./ERC8004ValidationRegistry.sol";
export type { erc8004ValidationRegistrySol };
import type * as verifiers from "./verifiers";
export type { verifiers };
export type { ERC8004IdentityRegistry } from "./ERC8004IdentityRegistry";
export type { ERC8004ReputationRegistry } from "./ERC8004ReputationRegistry";
export type { SentinelCore } from "./SentinelCore";
export type { SentinelLedger } from "./SentinelLedger";
export type { SentinelOFT } from "./SentinelOFT";
