/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SentinelLedger {
  export type LedgerEntryStruct = {
    timestamp: BigNumberish;
    entryType: BigNumberish;
    protocol: BigNumberish;
    amount: BigNumberish;
    riskScore: BigNumberish;
    zkProofHash: BytesLike;
    dataHash: BytesLike;
    confirmed: boolean;
  };

  export type LedgerEntryStructOutput = [
    timestamp: bigint,
    entryType: bigint,
    protocol: bigint,
    amount: bigint,
    riskScore: bigint,
    zkProofHash: string,
    dataHash: string,
    confirmed: boolean
  ] & {
    timestamp: bigint;
    entryType: bigint;
    protocol: bigint;
    amount: bigint;
    riskScore: bigint;
    zkProofHash: string;
    dataHash: string;
    confirmed: boolean;
  };
}

export interface SentinelLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "entries"
      | "entryCount"
      | "getEntries"
      | "getEntry"
      | "getStats"
      | "log"
      | "markAlertConfirmed"
      | "sentinelCore"
      | "totalAlerts"
      | "totalDefensiveActions"
      | "totalExposureUpdates"
      | "totalGeneric"
      | "totalPositionCloses"
      | "totalPositionOpens"
      | "totalProposalDrafts"
      | "totalRiskQueries"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "EntryConfirmed" | "EntryLogged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "entries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "entryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntries",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntry",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "log",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "markAlertConfirmed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sentinelCore",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAlerts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDefensiveActions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalExposureUpdates",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalGeneric",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPositionCloses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalPositionOpens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalProposalDrafts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRiskQueries",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "entries", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "entryCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEntries", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEntry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "log", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markAlertConfirmed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sentinelCore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAlerts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDefensiveActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalExposureUpdates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalGeneric",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPositionCloses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPositionOpens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProposalDrafts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRiskQueries",
    data: BytesLike
  ): Result;
}

export namespace EntryConfirmedEvent {
  export type InputTuple = [entryId: BigNumberish];
  export type OutputTuple = [entryId: bigint];
  export interface OutputObject {
    entryId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntryLoggedEvent {
  export type InputTuple = [
    entryId: BigNumberish,
    entryType: BigNumberish,
    protocol: BigNumberish,
    dataHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    entryId: bigint,
    entryType: bigint,
    protocol: bigint,
    dataHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    entryId: bigint;
    entryType: bigint;
    protocol: bigint;
    dataHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SentinelLedger extends BaseContract {
  connect(runner?: ContractRunner | null): SentinelLedger;
  waitForDeployment(): Promise<this>;

  interface: SentinelLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  entries: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string, string, boolean] & {
        timestamp: bigint;
        entryType: bigint;
        protocol: bigint;
        amount: bigint;
        riskScore: bigint;
        zkProofHash: string;
        dataHash: string;
        confirmed: boolean;
      }
    ],
    "view"
  >;

  entryCount: TypedContractMethod<[], [bigint], "view">;

  getEntries: TypedContractMethod<
    [from: BigNumberish, to: BigNumberish],
    [SentinelLedger.LedgerEntryStructOutput[]],
    "view"
  >;

  getEntry: TypedContractMethod<
    [entryId: BigNumberish],
    [SentinelLedger.LedgerEntryStructOutput],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        total: bigint;
        alerts: bigint;
        defensiveActions: bigint;
        proposalDrafts: bigint;
        riskQueries: bigint;
        exposureUpdates: bigint;
        positionOpens: bigint;
        positionCloses: bigint;
        generic: bigint;
      }
    ],
    "view"
  >;

  log: TypedContractMethod<
    [
      entryType: BigNumberish,
      protocol: BigNumberish,
      amount: BigNumberish,
      riskScore: BigNumberish,
      zkProofHash: BytesLike,
      dataHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  markAlertConfirmed: TypedContractMethod<
    [entryId: BigNumberish],
    [void],
    "nonpayable"
  >;

  sentinelCore: TypedContractMethod<[], [string], "view">;

  totalAlerts: TypedContractMethod<[], [bigint], "view">;

  totalDefensiveActions: TypedContractMethod<[], [bigint], "view">;

  totalExposureUpdates: TypedContractMethod<[], [bigint], "view">;

  totalGeneric: TypedContractMethod<[], [bigint], "view">;

  totalPositionCloses: TypedContractMethod<[], [bigint], "view">;

  totalPositionOpens: TypedContractMethod<[], [bigint], "view">;

  totalProposalDrafts: TypedContractMethod<[], [bigint], "view">;

  totalRiskQueries: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "entries"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, string, string, boolean] & {
        timestamp: bigint;
        entryType: bigint;
        protocol: bigint;
        amount: bigint;
        riskScore: bigint;
        zkProofHash: string;
        dataHash: string;
        confirmed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "entryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEntries"
  ): TypedContractMethod<
    [from: BigNumberish, to: BigNumberish],
    [SentinelLedger.LedgerEntryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEntry"
  ): TypedContractMethod<
    [entryId: BigNumberish],
    [SentinelLedger.LedgerEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        total: bigint;
        alerts: bigint;
        defensiveActions: bigint;
        proposalDrafts: bigint;
        riskQueries: bigint;
        exposureUpdates: bigint;
        positionOpens: bigint;
        positionCloses: bigint;
        generic: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "log"
  ): TypedContractMethod<
    [
      entryType: BigNumberish,
      protocol: BigNumberish,
      amount: BigNumberish,
      riskScore: BigNumberish,
      zkProofHash: BytesLike,
      dataHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "markAlertConfirmed"
  ): TypedContractMethod<[entryId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sentinelCore"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAlerts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDefensiveActions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalExposureUpdates"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalGeneric"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPositionCloses"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPositionOpens"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalProposalDrafts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRiskQueries"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EntryConfirmed"
  ): TypedContractEvent<
    EntryConfirmedEvent.InputTuple,
    EntryConfirmedEvent.OutputTuple,
    EntryConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "EntryLogged"
  ): TypedContractEvent<
    EntryLoggedEvent.InputTuple,
    EntryLoggedEvent.OutputTuple,
    EntryLoggedEvent.OutputObject
  >;

  filters: {
    "EntryConfirmed(uint256)": TypedContractEvent<
      EntryConfirmedEvent.InputTuple,
      EntryConfirmedEvent.OutputTuple,
      EntryConfirmedEvent.OutputObject
    >;
    EntryConfirmed: TypedContractEvent<
      EntryConfirmedEvent.InputTuple,
      EntryConfirmedEvent.OutputTuple,
      EntryConfirmedEvent.OutputObject
    >;

    "EntryLogged(uint256,uint8,uint256,bytes32,uint256)": TypedContractEvent<
      EntryLoggedEvent.InputTuple,
      EntryLoggedEvent.OutputTuple,
      EntryLoggedEvent.OutputObject
    >;
    EntryLogged: TypedContractEvent<
      EntryLoggedEvent.InputTuple,
      EntryLoggedEvent.OutputTuple,
      EntryLoggedEvent.OutputObject
    >;
  };
}
