/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SentinelCore {
  export type SentinelPositionStruct = {
    protocol: BigNumberish;
    amountUSD: BigNumberish;
    active: boolean;
    openedAt: BigNumberish;
  };

  export type SentinelPositionStructOutput = [
    protocol: bigint,
    amountUSD: bigint,
    active: boolean,
    openedAt: bigint
  ] & {
    protocol: bigint;
    amountUSD: bigint;
    active: boolean;
    openedAt: bigint;
  };

  export type MonitoredProtocolStruct = {
    name: string;
    contractAddr: AddressLike;
    exposureUSD: BigNumberish;
    active: boolean;
  };

  export type MonitoredProtocolStructOutput = [
    name: string,
    contractAddr: string,
    exposureUSD: bigint,
    active: boolean
  ] & {
    name: string;
    contractAddr: string;
    exposureUSD: bigint;
    active: boolean;
  };
}

export interface SentinelCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ALERT_THRESHOLD_USD"
      | "CRITICAL_THRESHOLD_USD"
      | "GAS_RESERVOIR_MIN"
      | "GAS_ROUTING_BPS"
      | "MAX_DEFENSIVE_POSITION"
      | "addProtocol"
      | "addToGasReservoir"
      | "agentWallet"
      | "closePosition"
      | "consumeGas"
      | "deactivateProtocol"
      | "emergencyDrainReservoir"
      | "fireAlert"
      | "gasReservoir"
      | "getPosition"
      | "getProtocol"
      | "logDefensiveAction"
      | "logProposalDraft"
      | "logRiskQuery"
      | "owner"
      | "protocolCount"
      | "protocols"
      | "registerPosition"
      | "renounceOwnership"
      | "sentinelPositions"
      | "setAgentWallet"
      | "totalAlerts"
      | "totalDefensiveActions"
      | "transferOwnership"
      | "updateExposure"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentWalletUpdated"
      | "AlertFired"
      | "DefensiveActionTaken"
      | "ExposureUpdated"
      | "GasConsumed"
      | "GasReservoirFunded"
      | "OwnershipTransferred"
      | "PositionRegistered"
      | "ProposalDrafted"
      | "ProtocolAdded"
      | "RiskQueryServed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ALERT_THRESHOLD_USD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CRITICAL_THRESHOLD_USD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GAS_RESERVOIR_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GAS_ROUTING_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_DEFENSIVE_POSITION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addProtocol",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addToGasReservoir",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agentWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closePosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "consumeGas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateProtocol",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyDrainReservoir",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fireAlert",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gasReservoir",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPosition",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProtocol",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logDefensiveAction",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "logProposalDraft",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "logRiskQuery",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocols",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPosition",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sentinelPositions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgentWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalAlerts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDefensiveActions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateExposure",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ALERT_THRESHOLD_USD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CRITICAL_THRESHOLD_USD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GAS_RESERVOIR_MIN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GAS_ROUTING_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_DEFENSIVE_POSITION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToGasReservoir",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agentWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "consumeGas", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyDrainReservoir",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fireAlert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gasReservoir",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logDefensiveAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logProposalDraft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logRiskQuery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocols", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sentinelPositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgentWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAlerts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDefensiveActions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateExposure",
    data: BytesLike
  ): Result;
}

export namespace AgentWalletUpdatedEvent {
  export type InputTuple = [oldAgent: AddressLike, newAgent: AddressLike];
  export type OutputTuple = [oldAgent: string, newAgent: string];
  export interface OutputObject {
    oldAgent: string;
    newAgent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AlertFiredEvent {
  export type InputTuple = [
    alertId: BigNumberish,
    protocolIndex: BigNumberish,
    exposureUSD: BigNumberish,
    riskScore: BigNumberish,
    isCritical: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    alertId: bigint,
    protocolIndex: bigint,
    exposureUSD: bigint,
    riskScore: bigint,
    isCritical: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    alertId: bigint;
    protocolIndex: bigint;
    exposureUSD: bigint;
    riskScore: bigint;
    isCritical: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DefensiveActionTakenEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    positionId: BigNumberish,
    protocol: BigNumberish,
    amountUSD: BigNumberish,
    action: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    actionId: bigint,
    positionId: bigint,
    protocol: bigint,
    amountUSD: bigint,
    action: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    actionId: bigint;
    positionId: bigint;
    protocol: bigint;
    amountUSD: bigint;
    action: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExposureUpdatedEvent {
  export type InputTuple = [
    index: BigNumberish,
    oldExposure: BigNumberish,
    newExposure: BigNumberish
  ];
  export type OutputTuple = [
    index: bigint,
    oldExposure: bigint,
    newExposure: bigint
  ];
  export interface OutputObject {
    index: bigint;
    oldExposure: bigint;
    newExposure: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasConsumedEvent {
  export type InputTuple = [amount: BigNumberish, remaining: BigNumberish];
  export type OutputTuple = [amount: bigint, remaining: bigint];
  export interface OutputObject {
    amount: bigint;
    remaining: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GasReservoirFundedEvent {
  export type InputTuple = [
    funder: AddressLike,
    amount: BigNumberish,
    newBalance: BigNumberish
  ];
  export type OutputTuple = [
    funder: string,
    amount: bigint,
    newBalance: bigint
  ];
  export interface OutputObject {
    funder: string;
    amount: bigint;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PositionRegisteredEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    protocol: BigNumberish,
    amountUSD: BigNumberish
  ];
  export type OutputTuple = [
    positionId: bigint,
    protocol: bigint,
    amountUSD: bigint
  ];
  export interface OutputObject {
    positionId: bigint;
    protocol: bigint;
    amountUSD: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalDraftedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    protocol: BigNumberish,
    descriptionHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    protocol: bigint,
    descriptionHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    protocol: bigint;
    descriptionHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolAddedEvent {
  export type InputTuple = [
    index: BigNumberish,
    name: string,
    contractAddr: AddressLike
  ];
  export type OutputTuple = [index: bigint, name: string, contractAddr: string];
  export interface OutputObject {
    index: bigint;
    name: string;
    contractAddr: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskQueryServedEvent {
  export type InputTuple = [
    queryId: BigNumberish,
    requester: AddressLike,
    protocol: BigNumberish,
    riskScore: BigNumberish,
    responseHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    queryId: bigint,
    requester: string,
    protocol: bigint,
    riskScore: bigint,
    responseHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    queryId: bigint;
    requester: string;
    protocol: bigint;
    riskScore: bigint;
    responseHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SentinelCore extends BaseContract {
  connect(runner?: ContractRunner | null): SentinelCore;
  waitForDeployment(): Promise<this>;

  interface: SentinelCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ALERT_THRESHOLD_USD: TypedContractMethod<[], [bigint], "view">;

  CRITICAL_THRESHOLD_USD: TypedContractMethod<[], [bigint], "view">;

  GAS_RESERVOIR_MIN: TypedContractMethod<[], [bigint], "view">;

  GAS_ROUTING_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_DEFENSIVE_POSITION: TypedContractMethod<[], [bigint], "view">;

  addProtocol: TypedContractMethod<
    [name: string, contractAddr: AddressLike],
    [void],
    "nonpayable"
  >;

  addToGasReservoir: TypedContractMethod<[], [void], "payable">;

  agentWallet: TypedContractMethod<[], [string], "view">;

  closePosition: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  consumeGas: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  deactivateProtocol: TypedContractMethod<
    [protocolIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyDrainReservoir: TypedContractMethod<[], [void], "nonpayable">;

  fireAlert: TypedContractMethod<
    [protocolIndex: BigNumberish, riskScore: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  gasReservoir: TypedContractMethod<[], [bigint], "view">;

  getPosition: TypedContractMethod<
    [positionId: BigNumberish],
    [SentinelCore.SentinelPositionStructOutput],
    "view"
  >;

  getProtocol: TypedContractMethod<
    [index: BigNumberish],
    [SentinelCore.MonitoredProtocolStructOutput],
    "view"
  >;

  logDefensiveAction: TypedContractMethod<
    [positionId: BigNumberish, action: string],
    [bigint],
    "nonpayable"
  >;

  logProposalDraft: TypedContractMethod<
    [
      proposalId: BigNumberish,
      protocolIndex: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;

  logRiskQuery: TypedContractMethod<
    [
      queryId: BigNumberish,
      requester: AddressLike,
      protocolIndex: BigNumberish,
      riskScore: BigNumberish,
      responseHash: BytesLike
    ],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  protocolCount: TypedContractMethod<[], [bigint], "view">;

  protocols: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        name: string;
        contractAddr: string;
        exposureUSD: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  registerPosition: TypedContractMethod<
    [
      positionId: BigNumberish,
      protocolIndex: BigNumberish,
      amountUSD: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sentinelPositions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, bigint] & {
        protocol: bigint;
        amountUSD: bigint;
        active: boolean;
        openedAt: bigint;
      }
    ],
    "view"
  >;

  setAgentWallet: TypedContractMethod<
    [newAgent: AddressLike],
    [void],
    "nonpayable"
  >;

  totalAlerts: TypedContractMethod<[], [bigint], "view">;

  totalDefensiveActions: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateExposure: TypedContractMethod<
    [protocolIndex: BigNumberish, newExposureUSD: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ALERT_THRESHOLD_USD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CRITICAL_THRESHOLD_USD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GAS_RESERVOIR_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GAS_ROUTING_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_DEFENSIVE_POSITION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addProtocol"
  ): TypedContractMethod<
    [name: string, contractAddr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addToGasReservoir"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "agentWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "closePosition"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "consumeGas"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateProtocol"
  ): TypedContractMethod<[protocolIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyDrainReservoir"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fireAlert"
  ): TypedContractMethod<
    [protocolIndex: BigNumberish, riskScore: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gasReservoir"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPosition"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [SentinelCore.SentinelPositionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProtocol"
  ): TypedContractMethod<
    [index: BigNumberish],
    [SentinelCore.MonitoredProtocolStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "logDefensiveAction"
  ): TypedContractMethod<
    [positionId: BigNumberish, action: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logProposalDraft"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      protocolIndex: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logRiskQuery"
  ): TypedContractMethod<
    [
      queryId: BigNumberish,
      requester: AddressLike,
      protocolIndex: BigNumberish,
      riskScore: BigNumberish,
      responseHash: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocols"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        name: string;
        contractAddr: string;
        exposureUSD: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerPosition"
  ): TypedContractMethod<
    [
      positionId: BigNumberish,
      protocolIndex: BigNumberish,
      amountUSD: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sentinelPositions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean, bigint] & {
        protocol: bigint;
        amountUSD: bigint;
        active: boolean;
        openedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAgentWallet"
  ): TypedContractMethod<[newAgent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalAlerts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDefensiveActions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateExposure"
  ): TypedContractMethod<
    [protocolIndex: BigNumberish, newExposureUSD: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentWalletUpdated"
  ): TypedContractEvent<
    AgentWalletUpdatedEvent.InputTuple,
    AgentWalletUpdatedEvent.OutputTuple,
    AgentWalletUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AlertFired"
  ): TypedContractEvent<
    AlertFiredEvent.InputTuple,
    AlertFiredEvent.OutputTuple,
    AlertFiredEvent.OutputObject
  >;
  getEvent(
    key: "DefensiveActionTaken"
  ): TypedContractEvent<
    DefensiveActionTakenEvent.InputTuple,
    DefensiveActionTakenEvent.OutputTuple,
    DefensiveActionTakenEvent.OutputObject
  >;
  getEvent(
    key: "ExposureUpdated"
  ): TypedContractEvent<
    ExposureUpdatedEvent.InputTuple,
    ExposureUpdatedEvent.OutputTuple,
    ExposureUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GasConsumed"
  ): TypedContractEvent<
    GasConsumedEvent.InputTuple,
    GasConsumedEvent.OutputTuple,
    GasConsumedEvent.OutputObject
  >;
  getEvent(
    key: "GasReservoirFunded"
  ): TypedContractEvent<
    GasReservoirFundedEvent.InputTuple,
    GasReservoirFundedEvent.OutputTuple,
    GasReservoirFundedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PositionRegistered"
  ): TypedContractEvent<
    PositionRegisteredEvent.InputTuple,
    PositionRegisteredEvent.OutputTuple,
    PositionRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProposalDrafted"
  ): TypedContractEvent<
    ProposalDraftedEvent.InputTuple,
    ProposalDraftedEvent.OutputTuple,
    ProposalDraftedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolAdded"
  ): TypedContractEvent<
    ProtocolAddedEvent.InputTuple,
    ProtocolAddedEvent.OutputTuple,
    ProtocolAddedEvent.OutputObject
  >;
  getEvent(
    key: "RiskQueryServed"
  ): TypedContractEvent<
    RiskQueryServedEvent.InputTuple,
    RiskQueryServedEvent.OutputTuple,
    RiskQueryServedEvent.OutputObject
  >;

  filters: {
    "AgentWalletUpdated(address,address)": TypedContractEvent<
      AgentWalletUpdatedEvent.InputTuple,
      AgentWalletUpdatedEvent.OutputTuple,
      AgentWalletUpdatedEvent.OutputObject
    >;
    AgentWalletUpdated: TypedContractEvent<
      AgentWalletUpdatedEvent.InputTuple,
      AgentWalletUpdatedEvent.OutputTuple,
      AgentWalletUpdatedEvent.OutputObject
    >;

    "AlertFired(uint256,uint256,uint256,uint8,bool,uint256)": TypedContractEvent<
      AlertFiredEvent.InputTuple,
      AlertFiredEvent.OutputTuple,
      AlertFiredEvent.OutputObject
    >;
    AlertFired: TypedContractEvent<
      AlertFiredEvent.InputTuple,
      AlertFiredEvent.OutputTuple,
      AlertFiredEvent.OutputObject
    >;

    "DefensiveActionTaken(uint256,uint256,uint256,uint256,string,uint256)": TypedContractEvent<
      DefensiveActionTakenEvent.InputTuple,
      DefensiveActionTakenEvent.OutputTuple,
      DefensiveActionTakenEvent.OutputObject
    >;
    DefensiveActionTaken: TypedContractEvent<
      DefensiveActionTakenEvent.InputTuple,
      DefensiveActionTakenEvent.OutputTuple,
      DefensiveActionTakenEvent.OutputObject
    >;

    "ExposureUpdated(uint256,uint256,uint256)": TypedContractEvent<
      ExposureUpdatedEvent.InputTuple,
      ExposureUpdatedEvent.OutputTuple,
      ExposureUpdatedEvent.OutputObject
    >;
    ExposureUpdated: TypedContractEvent<
      ExposureUpdatedEvent.InputTuple,
      ExposureUpdatedEvent.OutputTuple,
      ExposureUpdatedEvent.OutputObject
    >;

    "GasConsumed(uint256,uint256)": TypedContractEvent<
      GasConsumedEvent.InputTuple,
      GasConsumedEvent.OutputTuple,
      GasConsumedEvent.OutputObject
    >;
    GasConsumed: TypedContractEvent<
      GasConsumedEvent.InputTuple,
      GasConsumedEvent.OutputTuple,
      GasConsumedEvent.OutputObject
    >;

    "GasReservoirFunded(address,uint256,uint256)": TypedContractEvent<
      GasReservoirFundedEvent.InputTuple,
      GasReservoirFundedEvent.OutputTuple,
      GasReservoirFundedEvent.OutputObject
    >;
    GasReservoirFunded: TypedContractEvent<
      GasReservoirFundedEvent.InputTuple,
      GasReservoirFundedEvent.OutputTuple,
      GasReservoirFundedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PositionRegistered(uint256,uint256,uint256)": TypedContractEvent<
      PositionRegisteredEvent.InputTuple,
      PositionRegisteredEvent.OutputTuple,
      PositionRegisteredEvent.OutputObject
    >;
    PositionRegistered: TypedContractEvent<
      PositionRegisteredEvent.InputTuple,
      PositionRegisteredEvent.OutputTuple,
      PositionRegisteredEvent.OutputObject
    >;

    "ProposalDrafted(uint256,uint256,bytes32,uint256)": TypedContractEvent<
      ProposalDraftedEvent.InputTuple,
      ProposalDraftedEvent.OutputTuple,
      ProposalDraftedEvent.OutputObject
    >;
    ProposalDrafted: TypedContractEvent<
      ProposalDraftedEvent.InputTuple,
      ProposalDraftedEvent.OutputTuple,
      ProposalDraftedEvent.OutputObject
    >;

    "ProtocolAdded(uint256,string,address)": TypedContractEvent<
      ProtocolAddedEvent.InputTuple,
      ProtocolAddedEvent.OutputTuple,
      ProtocolAddedEvent.OutputObject
    >;
    ProtocolAdded: TypedContractEvent<
      ProtocolAddedEvent.InputTuple,
      ProtocolAddedEvent.OutputTuple,
      ProtocolAddedEvent.OutputObject
    >;

    "RiskQueryServed(uint256,address,uint256,uint8,bytes32,uint256)": TypedContractEvent<
      RiskQueryServedEvent.InputTuple,
      RiskQueryServedEvent.OutputTuple,
      RiskQueryServedEvent.OutputObject
    >;
    RiskQueryServed: TypedContractEvent<
      RiskQueryServedEvent.InputTuple,
      RiskQueryServedEvent.OutputTuple,
      RiskQueryServedEvent.OutputObject
    >;
  };
}
