/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ERC8004ValidationRegistry {
  export type ValidationEntryStruct = {
    agentId: BigNumberish;
    batchId: BytesLike;
    proofCalldata: BytesLike;
    verifierContract: AddressLike;
    submitter: AddressLike;
    timestamp: BigNumberish;
    verified: boolean;
  };

  export type ValidationEntryStructOutput = [
    agentId: bigint,
    batchId: string,
    proofCalldata: string,
    verifierContract: string,
    submitter: string,
    timestamp: bigint,
    verified: boolean
  ] & {
    agentId: bigint;
    batchId: string;
    proofCalldata: string;
    verifierContract: string;
    submitter: string;
    timestamp: bigint;
    verified: boolean;
  };
}

export interface ERC8004ValidationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentBatches"
      | "getBatchCount"
      | "getValidation"
      | "isValidated"
      | "isVerified"
      | "owner"
      | "submitValidation"
      | "totalValidations"
      | "validations"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ValidationSubmitted" | "ValidationVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentBatches",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBatchCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getValidation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isValidated",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "submitValidation",
    values: [BigNumberish, BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalValidations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validations",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "agentBatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBatchCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalValidations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validations",
    data: BytesLike
  ): Result;
}

export namespace ValidationSubmittedEvent {
  export type InputTuple = [
    agentId: BigNumberish,
    batchId: BytesLike,
    verifierContract: AddressLike,
    submitter: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    agentId: bigint,
    batchId: string,
    verifierContract: string,
    submitter: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    agentId: bigint;
    batchId: string;
    verifierContract: string;
    submitter: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidationVerifiedEvent {
  export type InputTuple = [
    batchId: BytesLike,
    success: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    batchId: string,
    success: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    batchId: string;
    success: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC8004ValidationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ERC8004ValidationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ERC8004ValidationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentBatches: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  getBatchCount: TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;

  getValidation: TypedContractMethod<
    [batchId: BytesLike],
    [ERC8004ValidationRegistry.ValidationEntryStructOutput],
    "view"
  >;

  isValidated: TypedContractMethod<[batchId: BytesLike], [boolean], "view">;

  isVerified: TypedContractMethod<[batchId: BytesLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  submitValidation: TypedContractMethod<
    [
      agentId: BigNumberish,
      batchId: BytesLike,
      proofCalldata: BytesLike,
      verifierContract: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  totalValidations: TypedContractMethod<[], [bigint], "view">;

  validations: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, string, string, string, bigint, boolean] & {
        agentId: bigint;
        batchId: string;
        proofCalldata: string;
        verifierContract: string;
        submitter: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentBatches"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBatchCount"
  ): TypedContractMethod<[agentId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getValidation"
  ): TypedContractMethod<
    [batchId: BytesLike],
    [ERC8004ValidationRegistry.ValidationEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isValidated"
  ): TypedContractMethod<[batchId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[batchId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "submitValidation"
  ): TypedContractMethod<
    [
      agentId: BigNumberish,
      batchId: BytesLike,
      proofCalldata: BytesLike,
      verifierContract: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalValidations"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "validations"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, string, string, string, bigint, boolean] & {
        agentId: bigint;
        batchId: string;
        proofCalldata: string;
        verifierContract: string;
        submitter: string;
        timestamp: bigint;
        verified: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ValidationSubmitted"
  ): TypedContractEvent<
    ValidationSubmittedEvent.InputTuple,
    ValidationSubmittedEvent.OutputTuple,
    ValidationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ValidationVerified"
  ): TypedContractEvent<
    ValidationVerifiedEvent.InputTuple,
    ValidationVerifiedEvent.OutputTuple,
    ValidationVerifiedEvent.OutputObject
  >;

  filters: {
    "ValidationSubmitted(uint256,bytes32,address,address,uint256)": TypedContractEvent<
      ValidationSubmittedEvent.InputTuple,
      ValidationSubmittedEvent.OutputTuple,
      ValidationSubmittedEvent.OutputObject
    >;
    ValidationSubmitted: TypedContractEvent<
      ValidationSubmittedEvent.InputTuple,
      ValidationSubmittedEvent.OutputTuple,
      ValidationSubmittedEvent.OutputObject
    >;

    "ValidationVerified(bytes32,bool,uint256)": TypedContractEvent<
      ValidationVerifiedEvent.InputTuple,
      ValidationVerifiedEvent.OutputTuple,
      ValidationVerifiedEvent.OutputObject
    >;
    ValidationVerified: TypedContractEvent<
      ValidationVerifiedEvent.InputTuple,
      ValidationVerifiedEvent.OutputTuple,
      ValidationVerifiedEvent.OutputObject
    >;
  };
}
