/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC8004ValidationRegistry } from "./ERC8004ValidationRegistry";
export type { IVerifier } from "./IVerifier";
